### ISSUE TITLE
scaproc_analyse - %varlist macro reference missing

### ISSUE THREAD

**Issue by RuhindKI** [philipmason/Wood-Street-Consultants#1]
Good Day, 

Could you please include the %varlist macro program used in the scaproc_analyse program. Thank you in advance. 

Error message: 
WARNING: Apparent invocation of macro VARLIST not resolved.

**Comment by argenx-pmason** [comment]
I added varlist macro in.

**Comment by RuhindKI** [comment]
Thank you!
